[package]
name = "vicar"
version = "0.1.0"
edition = "2021"
authors = ["Kevin M. Gill <apoapsys@gmail.com>"]
description = "VICAR file format support"
license = "MIT" 

[[bin]]
name = "main"
path = "bin/main.rs"

[lib]
name = "vicar"

[dependencies]
sciimg = "0.2.10"
memmap = "0.7.0"